### ISSUE TITLE
Specialisation for builtin type, without static lifetime constraint?

### ISSUE THREAD

**Issue by NobodyXu** [sagebind/castaway#5]
Is it possible to create a macro to specialise for bultin types like `bool`, `char`, `i32`, `NonZeroU32`, `&str`, `String` and `Cow<'_, str>` without the static lifetime constraint?

**Comment by sagebind** [comment]
No, that is one of the limitations of Castaway's approach, as it relies on [`TypeId`](https://doc.rust-lang.org/stable/std/any/struct.TypeId.html) to verify that two given types are equal, which is limited to `'static` type constraints. This is because from its perspective, `&'static str` and `&'a str` are of the same type for some value of `'a`, but that does _not_ mean it is safe to cast an `&'a str` to `&'static str`; that would unsafely extend the lifetime of the borrow!

Now in limited circumstances this might actually be OK; it would be safe to allow you to _try_ to cast an arbitrary `T` to a specific `U` if their types were equal, and `U` is known to not contain any lifetime parameters. If it does not contain any lifetime parameters, then `T` _must_ be `'static`, and therefore `T == U`. This is impossible to implement generically as there's no contraint that could be used to check that. However, I had not thought of doing this on a case-by-case basis before; it might complicate it a bit but I could see the use case, and might be possible to implement.

Note that if it were possible and we did decide to implement something like this, types containing lifetimes would be strictly off the table for safety reasons, so `&str` and `Cow<'_, str>` would not be allowed as cast destinations. But primitive owned types might be allowed such as `bool`.

I'll have to think about how this could be implemented, and if so, how we might expose it. It is theoretically possible.

**Comment by NobodyXu** [comment]
Just as my two cents, but maybe we could use `type_name` to check whether it is a builtin types?

While it does not guarantee uniqueness, I doubt that `type_name::<i32>()` would produce anything other than `"i32"`.
Same for other primitive types, like `bool`, `char`, `NonZeroU32` and etc.

**Comment by sagebind** [comment]
`type_name` is not a sufficient check by itself as it does not guarantee uniqueness across all types. For example, I might define my own struct named `i32`, and `type_name` _might_ return an identical string for my struct and the builtin `i32` primitive, and boom! Undefined behavior.

**Comment by NobodyXu** [comment]
Then what about this:

```
use std::any::type_name;

fn f<T>(_: T) {}

fn type_name_of<T>(_: T) -> &'static str {
    type_name::<T>()
}

fn is_same_type<T, U>() -> bool {
    type_name_of(f::<T>) == type_name_of(f::<U>)
}
```

**Comment by sagebind** [comment]
Same problem. If I define a `struct i32`, it is perfectly within `type_name`'s contract to return `"f::<i32>"` for both `f::<std::primitive::i32>` and `f::<crate::i32>`. _Currently_ it returns different strings, but the docs are very explicit that there are no stability guarantee on the format of the string returned.

Under the hood Castaway uses `transmute_copy` which is one of the riskiest `unsafe` intrinsics that Rust offers. When you're playing with fire there's no room "good enough". In order to be safe, Castway has to offer a 100% correctness guarantee for every cast, and `type_name` does not offer sufficient guarantees for that by itself.

**Comment by NobodyXu** [comment]
@sagebind You are right about `type_name`, it is totally unusable for casting.

If we can use [`std::intrinsics::type_id`](https://doc.rust-lang.org/std/intrinsics/fn.type_id.html) on stable, then things it going to be much easier...

**Comment by sagebind** [comment]
After some experimentation it seems possible to expose this for a fixed subset of lifetime-free types. The hard part is making it compile and usable under a reasonable API: https://github.com/sagebind/castaway/pull/6

**Comment by sagebind** [comment]
This is now possible for some types in the [0.2 release](https://github.com/sagebind/castaway/releases/tag/0.2.0).
